### ISSUE TITLE
Can I copy someone server?

### ISSUE THREAD

**Issue by BlackWhite321** [Jisagi/Discord-guild-copy#122] opened 2022-01-29 18:52 UTC
Hello, can I copy someone server where I don't have admin permission by this tool?

BTW. I can see this tool doesn't work correctly. I fixed it this way: Replace this line:
const client = new Discord.Client({ intents: ['GUILDS', 'GUILD_MEMBERS'] });
on:
const client = new Discord.Client({ intents: [""] })

**Comment by Jisagi** [comment] 2022-01-29 19:12
> Hello, can I copy someone server where I don't have admin permission by this tool?
No, you cannot do that. You have to have a Bot account on a guild to copy it and there for you either need Admin permissions yourself or someone else with them.

> BTW. I can see this tool doesn't work correctly. I fixed it this way: Replace this line:
const client = new Discord.Client({ intents: ['GUILDS', 'GUILD_MEMBERS'] });
on:
const client = new Discord.Client({ intents: [""] })

That part is not incorrect, why should it not work? The bot just doesn't need more than those 2 intents.

**Comment by BlackWhite321** [comment] 2022-01-29 19:32
> That part is not incorrect, why should it not work? The bot just doesn't need more than those 2 intents.

It didn't work for me, so maybe it would be helpful for someone who has similar issue.

**Comment by Jisagi** [comment] 2022-01-29 19:59
Ok, I see where the problem is. I will push a fix in a second to fix this.

**Comment by Jisagi** [comment] 2022-01-29 20:03
Ok, should be fixed now. They did "change" the intents again

**Closed** 2022-01-29 20:02 UTC
