### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by Creston1** [Jisagi/Discord-guild-copy#19] opened 2018-08-23 06:10 UTC
I have installed discord.js using npm install, and not npm install discord.js.

SS: https://i.imgur.com/DrvW1W6.png

**Comment by Jisagi** [comment] 2018-08-23 17:28
I am on it, give me the time to fix this. Seems to be an update on the api side. I have to see when i get to fixing it.

**Comment by NDAfternoon** [comment] 2018-08-23 17:59
thanks!

**Comment by NDAfternoon** [comment] 2018-08-23 18:05
lol was able to kinda fix it
https://imgur.com/a/Ux9HJlZ

**Comment by Jisagi** [comment] 2018-08-23 18:07
I already know what the problem is but i can't commit it right now since i'm on my phone and i need to update the version check as well which i can't do on mobile either 😉

**Comment by fofoiraq** [comment] 2018-08-23 23:50
NDAfternoon Can u Help For this I needed to much

**Comment by Jisagi** [comment] 2018-08-24 08:59
Should be fixed with this commit now https://github.com/Jisagi/Discord-guild-copy/commit/6137f16ad441843daf0356fbd409d37e9a0288ae

**Comment by Jisagi** [comment] 2018-08-28 14:50
Closing this now. If the problem should still occur, feel free to reopen the issue.

**Closed by Jisagi** 2018-08-28 14:50 UTC
