### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by DonaldDumq** [Jisagi/Discord-guild-copy#8] opened 2018-05-11 02:20 UTC
[11.05.2018 02:01:40] undefined
[11.05.2018 02:04:11] undefined
[11.05.2018 02:06:20] undefined
[11.05.2018 02:08:41] TypeError: newGuildAdminRole.permissions.has is not a function
    at Function.validateSettings (/root/guildcopy/objects/validator.js:35:44)
    at Client.client.on (/root/guildcopy/copy.js:34:41)
    at Client.emit (events.js:187:15)
    at WebSocketConnection.triggerReady (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (/root/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/root/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/root/node_modules/ws/lib/event-target.js:120:16)
[11.05.2018 02:10:01] TypeError: newGuildAdminRole.permissions.has is not a function
    at Function.validateSettings (/root/guildcopy/objects/validator.js:35:44)
    at Client.client.on (/root/guildcopy/copy.js:34:41)
    at Client.emit (events.js:187:15)
    at WebSocketConnection.triggerReady (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (/root/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/root/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/root/node_modules/ws/lib/event-target.js:120:16)
[11.05.2018 02:13:08] TypeError: guild.iconURL is not a function
    at Function.getGeneralData (/root/guildcopy/objects/serializer.js:71:25)
    at Function.serializeOldGuild (/root/guildcopy/objects/serializer.js:22:34)
    at Client.client.on (/root/guildcopy/copy.js:55:36)
    at Client.emit (events.js:187:15)
    at WebSocketConnection.triggerReady (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (/root/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/root/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
[11.05.2018 02:13:20] TypeError: newGuildAdminRole.permissions.has is not a function
    at Function.validateSettings (/root/guildcopy/objects/validator.js:35:44)
    at Client.client.on (/root/guildcopy/copy.js:34:41)
    at Client.emit (events.js:187:15)
    at WebSocketConnection.triggerReady (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (/root/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/root/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/root/node_modules/ws/lib/event-target.js:120:16)
[11.05.2018 02:13:34] TypeError: newGuildAdminRole.permissions.has is not a function
    at Function.validateSettings (/root/guildcopy/objects/validator.js:35:44)
    at Client.client.on (/root/guildcopy/copy.js:34:41)
    at Client.emit (events.js:187:15)
    at WebSocketConnection.triggerReady (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (/root/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/root/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/root/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/root/node_modules/ws/lib/event-target.js:120:16)

**Comment by Jisagi** [comment] 2018-05-11 09:02
First, please don't open two issues for the same error!

Check if nodejs is update and >= v8.x.x.
Please also make sure you installed discord.js with the provided package.json by using `npm install`, otherwise you will get the d.js stable release which will not work!

I have seen this error already but could not reproduce it at all. Provide as many information as possible, otherwise i will not be able to help.

**Comment by DonaldDumq** [comment] 2018-05-11 16:14
What is your discord? I will friend request you or add me Generic#5686

**Comment by Jisagi** [comment] 2018-05-11 16:51
Fixed in DMs.
Solution: reinstall nodejs ¯\_(ツ)_/¯

**Closed by Jisagi** 2018-05-11 16:51 UTC
