### ISSUE TITLE
Doesn't work, says "undefined"

### ISSUE THREAD

**Issue by zakkor** [Jisagi/Discord-guild-copy#12] opened 2018-05-23 23:24 UTC
Perhaps this is the cue for better error handling.
Let me know if there's any way I can help

**Comment by Jisagi** [comment] 2018-05-24 08:13
You have no provide more info than just "doesnt work, says undefined". There are error logs inside `logs/`, those might actually tell me something.

**Comment by nxtVentix** [comment] 2018-05-24 21:09
[24.05.2018 23:06:09] undefined
[24.05.2018 23:06:44] undefined
[24.05.2018 23:07:25] undefined
[24.05.2018 23:08:35] undefined

**Comment by Jisagi** [comment] 2018-05-24 21:12
How do you think should i know how this happens? As i said, provide more details, enable the debug mode in the settings and post a stack dump. Just posting a few undefined won't help anybody debugging this.

**Comment by nxtVentix** [comment] 2018-05-24 21:13
Debug is always true!

**Comment by nxtVentix** [comment] 2018-05-24 21:14
`PS C:\Users\benny\Downloads\Discord-guild-copy-master> npm install
npm WARN discord.js@12.0.0-dev requires a peer of bufferutil@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of libsodium-wrappers@^0.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of sodium@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of zlib-sync@^0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN prism-media@0.2.1 requires a peer of opusscript@^0.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN prism-media@0.2.1 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN guildcopy@1.0.0 No repository field.

up to date in 1.077s
PS C:\Users\benny\Downloads\Discord-guild-copy-master>`

**Comment by nxtVentix** [comment] 2018-05-24 21:15
![1212](https://user-images.githubusercontent.com/20678496/40514109-49debd96-5fa8-11e8-9bb2-212bc6075bbd.PNG)

**Comment by Jisagi** [comment] 2018-05-24 21:15
that's not a stack dump but the output of npm install. that's also nothing helpful. maybe upload the full logs

**Comment by nxtVentix** [comment] 2018-05-24 21:16
That is the full log!

**Comment by Jisagi** [comment] 2018-05-24 21:17
Which nodejs version do you have?

**Comment by nxtVentix** [comment] 2018-05-24 21:17
ive downloaded nodejs today, the latest.!

**Comment by Jisagi** [comment] 2018-05-24 21:20
Latest is not a version number, there are multiple version on their website but as long as it's >=8.0.0.
Anyway, i cannot reproduce this with nodejs 8, 9 or 10 when i download a fresh version of the repository.
might wanna redownload the repository and recheck all settings

**Comment by nxtVentix** [comment] 2018-05-24 21:21
i hat: `v10.2.1`

**Comment by nxtVentix** [comment] 2018-05-24 21:22
i downgraded to: `8.11.2 LTS` same problem!

**Comment by nxtVentix** [comment] 2018-05-24 21:26
doesnt work ;( but if i type `npm install` ` yourself.
npm WARN guildcopy@1.0.0 No repository field.`

**Comment by Jisagi** [comment] 2018-05-24 21:28
Check your npm version with `npm -v` and maybe update it with `npm update -g npm`.
Latest should be 6.0.X

**Comment by nxtVentix** [comment] 2018-05-24 21:29
`5.6.0`

**Comment by Jisagi** [comment] 2018-05-24 21:30
Does npm at least intall the packages? a warn doesn't mean it wasn't successful

**Comment by nxtVentix** [comment] 2018-05-24 21:31
i typed the command and checked the version, same.

**Comment by nxtVentix** [comment] 2018-05-24 21:31
now i will try: `npm install -g npm@latest`

**Comment by shikhir-arora** [comment] 2018-05-24 21:31
Are you sure you set up your settings.json file correctly? If you're getting undefined errors when it runs this is probably where the error lies..

**Comment by nxtVentix** [comment] 2018-05-24 21:32
yes, i get the error directly by start!

**Comment by Jisagi** [comment] 2018-05-24 21:33
I agree with @shikhir-arora here. I has to be misuse rather than a script issue at this point.

**Comment by nxtVentix** [comment] 2018-05-24 21:37
it works now. thank you!

**Comment by Jisagi** [comment] 2018-05-24 21:40
Since this was created by @zakkor :
1. redownload a fresh version of the repository
2. check your settings.config
3. make sure you have a nodejs version >=8.0.0

I'll close this for now. If the error should still occur, feel free to reopen it.

**Closed by Jisagi** 2018-05-24 21:40 UTC

**Comment by zakkor** [comment] 2018-05-24 22:50
@nxtVentix what was wrong in your settings.json?
